[workspace]
resolver = "2"
members = [
    "crates/openrscad-syntax",
    "crates/openrscad-ir",
    "crates/openrscad-eval",
    "crates/openrscad-geom",
    "crates/openrscad-cli",
    "crates/openrscad-wasm",
    "crates/openrscad-lsp",
    "xtask",
]

[workspace.package]
version = "0.11.0-beta.2"
edition = "2021"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/matthova/openrscad"
rust-version = "1.85"

[workspace.dependencies]
openrscad-syntax = { path = "crates/openrscad-syntax" }
openrscad-ir = { path = "crates/openrscad-ir" }
openrscad-eval = { path = "crates/openrscad-eval" }
openrscad-geom = { path = "crates/openrscad-geom" }

logos = "0.15"
thiserror = "2"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
rustc-hash = "2"
ttf-parser = "0.25"
earcutr = "0.4"
geo = "0.29"
png = { version = "0.17", default-features = false }
miniz_oxide = "0.8"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
