[package]
name = "openrscad-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "openrscad"
path = "src/main.rs"

[dependencies]
openrscad-syntax = { workspace = true }
openrscad-eval = { workspace = true, features = ["system-fonts"] }
openrscad-geom = { workspace = true }
openrscad-ir = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
png = { workspace = true }
